### ISSUE TITLE
Problem while reading keys 

### ISSUE THREAD

**Issue by mbartecki** [lissy93/twitter-sentiment-visualisation#15]
Hi 
When I'm performing search I'm getting an error like below. Page is loaded with sentiment hexagons only and process is crashed/down. 
/../sentiment/twitter-sentiment-visualisation/routes/entity-api.js:21
    ref = Object.keys(data);
                 ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at formatData (/../sentiment/twitter-sentiment-visualisation/routes/entity-api.js:21:18)

My keys.js file looks like below: 
(function() {
  exports.twitter = {
    consumer_key: 'CCdQ24zCJFfsdG4vG5tPK9qHWhQ',
    consumer_secret: '3tz4HtaXVy6WsfsmtZwyq3i0SonfffFgZ4p4UL1fQCRJ3',
    token: '412355982-u0aNeaPTzljreffH0sseORffffff16zpjuwDFH',
    token_secret: 'ubqRht1aDQ5cHUffffEuNWNVDYfsmrffffn725Fr'
  };
  exports.googlePlaces = 'AIzaSyAsfesfOWg2XhA9Uam0Gn3rydpXXffffOyOvQ';
  exports.hp = '8fea4345-6d9c-4832-b70f-29d0ac7ffffe4';
  exports.watson = { username: '0d747458-27c9-4e26-9461-48ef7bee116c', password:'hj3HEVffff3'};

}).call(this);
(Of course I've masked credentials data :))
Can you suggest some solution ?

**Comment by mbartecki** [comment]
More about the issue - it works for some queries and for others is crashing. As an example in search "Miroslaw Bartecki" and error  
/sentiment/twitter-sentiment-visualisation/routes/entity-api.js:21
    ref = Object.keys(data);
                 ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at formatData (/sentiment/twitter-sentiment-visualisation/routes/entity-api.js:21:18)
    at /sentiment/twitter-sentiment-visualisation/routes/entity-api.js:37:23
    at Request._callback (/sentiment/twitter-sentiment-visualisation/node_modules/haven-entity-extraction/index.js:64:16)
    at Request.self.callback (/sentiment/twitter-sentiment-visualisation/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/sentiment/twitter-sentiment-visualisation/node_modules/request/request.js:1163:10)

**Comment by lissy93** [comment]
This doesn't seem to be a reproducible, or re-occurring problem, so unless you can provide some further info, or steps to reproduce, closing for now
