### ISSUE TITLE
Error: Cannot find module '../public/data/all_sentiment_results_edwardsnowdon.json'

### ISSUE THREAD

**Issue by isathish** [lissy93/twitter-sentiment-visualisation#21]
npm start

> twitter-sentiment-visualisation@1.5.0 start /Users/sathish/ORION/Sentiment/twitter-sentiment-visualisation
> node ./bin/www

module.js:557
    throw err;
    ^

Error: Cannot find module '../public/data/all_sentiment_results_edwardsnowdon.json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sathish/ORION/Sentiment/twitter-sentiment-visualisation/routes/sa-comparison.js:8:16)
    at Object.<anonymous> (/Users/sathish/ORION/Sentiment/twitter-sentiment-visualisation/routes/sa-comparison.js:86:4)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sathish/ORION/Sentiment/twitter-sentiment-visualisation/app.js:70:33)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-sentiment-visualisation@1.5.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twitter-sentiment-visualisation@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sathish/.npm/_logs/2018-02-14T07_36_11_410Z-debug.log

**Comment by lissy93** [comment]
You need to run the build scripts, to generate these files. 
Here are the build instructions: https://github.com/Lissy93/twitter-sentiment-visualisation/blob/dev/docs/installation-instructions.md
