### ISSUE TITLE
Unable to restart project without port number error.

### ISSUE THREAD

**Issue by Murasaki-Z** [lissy93/twitter-sentiment-visualisation#4]
The project runs fine on the first go. But stopping it with Ctrl+C and restarting it(using npm start) produces 
```
events.js: 161
    throw er; //Unhandled 'error' event
```

I am able to rectify the error by restarting my system.

**Comment by lissy93** [comment]
Hi,
That's odd - seems to work ok for me. Can you paste full stack-trace?

**Comment by Murasaki-Z** [comment]
```
npm start 

> twitter-sentiment-visualisation@0.0.1 start /home/batman/twitter-sentiment-visualisation 
> node ./bin/www 

events.js:161 
      throw er; // Unhandled 'error' event 
      ^ 

Error: listen EADDRINUSE :::8080 
    at Object.exports._errnoException (util.js:1023:11) 
    at exports._exceptionWithHostPort (util.js:1046:20) 
    at Server._listen2 (net.js:1261:14) 
    at listen (net.js:1297:10) 
    at Server.listen (net.js:1375:9) 
    at Object.<anonymous> (/home/batman/twitter-sentiment-visualisation/app.js:18:8) 
    at Module._compile (module.js:571:32) 
    at Object.Module._extensions..js (module.js:580:10) 
    at Module.load (module.js:488:32) 
    at tryModuleLoad (module.js:447:12) 
    at Function.Module._load (module.js:439:3) 
    at Module.require (module.js:498:17) 
    at require (internal/module.js:20:19) 
    at Object.<anonymous> (/home/batman/twitter-sentiment-visualisation/bin/www:7:11) 
    at Module._compile (module.js:571:32) 
    at Object.Module._extensions..js (module.js:580:10) 

```

**Comment by lissy93** [comment]
That's because you haven't killed the first instance before running the second. 
Since it is not possible to use the same port simultaneously, you can change port number in `server-side-source/config/app-config.coffee` then rebuild and run.
